name: "cma-holereacher"
overwrite: True
save_path: "experiments"

env: "HoleReacher-v0"
env_params:
  wrappers:
    - alr_envs.utils.dmp_env_wrapper.DmpEnvWrapper
  wrapper_params:
    - 'num_dof:5 num_basis:5 duration:2 learn_goal:True policy_type:"velocity" alpha_phase:2'
  n_envs: 8
  vecenv_params:
    n_samples: 14
    context: 'spawn'
    shared_memory: False
    worker: alr_envs.utils.dmp_async_vec_env._worker

algorithm: "cma"
algo_params:
  inopts:
    popsize: 14
  init_sigma: 0.1

n_timesteps: 500



