name: "ppo-holereacher"
save_path: "experiments"

env: 'InformedHoleReacher-v0'
env_params:
  wrappers:
    - sb3_contrib.common.wrappers.TimeFeatureWrapper
    - stable_baselines3.common.vec_env.VecNormalize
  wrapper_params:
    - ''
    - 'gamma:0.99'
  n_envs: 8
  
algorithm: "ppo"   
algo_params: 
  policy: 'MlpPolicy'
  batch_size: 8
  n_steps: 64
  gamma: 0.99
  gae_lambda: 1.0
  n_epochs: 5
  ent_coef: 2.e-4
  learning_rate: 2.e-4
  clip_range: 0.4
  max_grad_norm: 5
  vf_coef: 0.42
  verbose: 1

n_timesteps: 1.e+6