name: "ppo-holereacher"
save_path: "experiments"

env: 'InformedHoleReacher-v0'
env_params:
  wrappers:
    - sb3_contrib.common.wrappers.TimeFeatureWrapper
    - stable_baselines3.common.vec_env.VecNormalize
  wrapper_params:
    - ''
    - 'gamma:0.99'
  n_envs: 8
  
algo_params:
  policy: 'MlpPolicy'
  batch_size: 16
  n_steps: 128
  gamma: 0.99
  gae_lambda: 0.95
  n_epochs: 10
  ent_coef: 0.0
  learning_rate: 0.0001
  clip_range: 0.2
  max_grad_norm: 0.5
  vf_coef: 0.5
  verbose: 1

n_timesteps: 2e7
