name: "cma-reacher"
overwrite: True
save_path: "experiments"

env: "Reacher-v2"
env_params:
  wrappers:
    - t5.wrappers.CmaReacherWrapper
    - alr_envs.utils.dmp_env_wrapper.DmpEnvWrapperVel
  wrapper_params:
    - ''
    - 'num_dof:2 num_basis:5 duration:1 dt:0.02 learn_goal:True'
  n_envs: 1
  vecenv_params:
    n_samples: 14
    context: 'spawn'
    shared_memory: False
    worker: alr_envs.utils.dmp_async_vec_env._worker

algorithm: "cma"
algo_params:
  inopts:
    popsize: 14
  init_sigma: 0.1

n_timesteps: 500



