name: "ppo-reacher"

env: "Reacher-v2" 
env_params:
  wrappers:
    - sb3_contrib.common.wrappers.TimeFeatureWrapper
    - stable_baselines3.common.vec_env.VecNormalize
  wrapper_params:
    - ''
    - 'gamma:0.99'
  n_envs: 16
  
algorithm: "ppo"   
algo_params: 
  policy: 'MlpPolicy'
  batch_size: 256
  n_steps: 1024
  gamma: 0.99
  gae_lambda: 0.98
  n_epochs: 10
  ent_coef: 0.0
  learning_rate: 8.e-4
  clip_range: 0.1
  max_grad_norm: 0.9
  vf_coef: 0.7

n_timesteps: 1.e+6